### PR TITLE
linux support

### PR DESCRIPTION
**Pull request by nkruzan**
would it be preferred to break out instructions like this or just mix linux examples in

### CODE REVIEW

**Comment by calebmarting** [comment]
> would it be preferred to break out instructions like this or just mix linux examples in

I think breaking it out makes the most sense. In the actual makefiles and stuff we should try to make it detect OS and run the correct commands.

**Comment by nkruzan** [comment]
still compatibility issues

**Comment by nkruzan** [comment]
i also had to modify BlueNRG1.h and system_bluenrg1.c due to case-sensitivity. not sure best way to handle that

**Comment by jmrharris** [comment]
Hi @nkruzan - I just grabbed the Makefile from your fork, updated the incorrectly cased filenames in the ST library, and it built first go! Thanks.

**Comment by nkruzan** [comment]
> Hi @nkruzan - I just grabbed the Makefile from your fork, updated the incorrectly cased filenames in the ST library, and it built first go! Thanks.

Thanks for the feedback, I have marked for review, but I am sure there is room for improvement.

**Review by calebmarting — APPROVED** [review]

**Pull request merged**
